# Generated by Django 5.1.5 on 2025-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumini', '0002_alumnipost_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_posts/'),
        ),
    ]
