# Generated by Django 5.1.5 on 2025-01-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumini', '0003_alter_alumnipost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipost',
            name='photo',
            field=models.ImageField(upload_to='alumni_posts/'),
        ),
    ]
