# Generated by Django 5.1.5 on 2025-01-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumini', '0004_alter_alumnipost_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
