# Generated by Django 5.0.2 on 2024-09-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('water', 'Water Problem'), ('electricity', 'Electricity Issue'), ('cleaning', 'Cleaning Issue'), ('other', 'Other')], max_length=50)),
                ('custom_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('arrived', 'Arrived'), ('working', 'Working'), ('solved', 'Solved')], default='arrived', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
