# Generated by Django 5.0.1 on 2025-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Management', '0002_alter_ticket_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('Company Policies', 'Company Policies'), ('Salary Delays', 'Salary Delays'), ('Workload Pressure', 'Workload Pressure'), ('Workplace Harassment', 'Workplace Harassment'), ('Software Bugs', 'Software Bugs'), ('Technical Support', 'Technical Support'), ('Job Role Mismatch', 'Job Role Mismatch'), ('Project Deadlines', 'Project Deadlines'), ('Performance Reviews', 'Performance Reviews'), ('Team Collaboration', 'Team Collaboration')], max_length=50),
        ),
    ]
