# Generated by Django 5.0.2 on 2025-03-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='job',
            name='Description',
            field=models.TextField(default='No description available'),
        ),
    ]
