# Generated by Django 5.0.2 on 2025-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Management', '0002_remove_job_application_deadline_remove_job_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
