# Generated by Django 5.0.2 on 2025-03-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Management', '0003_job_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_name',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='employment_status',
            new_name='Job_Experience',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='Job_Role',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_location',
            new_name='Location',
        ),
    ]
