# Generated by Django 5.0.2 on 2025-03-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Management', '0004_rename_company_name_job_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
    ]
